# Generated by Django 2.1.7 on 2019-04-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '领域信息',
                'verbose_name_plural': '领域信息',
                'db_table': 'area',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('DBLP', models.URLField(blank=True, null=True)),
                ('Href', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '会议信息',
                'verbose_name_plural': '会议信息',
                'db_table': 'conference',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Area')),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Conference')),
            ],
            options={
                'verbose_name': '会议-领域信息',
                'verbose_name_plural': '会议-领域信息',
                'db_table': 'conference_area',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('homepage', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
                'db_table': 'institution',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('href', models.URLField(max_length=500)),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Conference')),
            ],
            options={
                'verbose_name': '论文信息',
                'verbose_name_plural': '论文信息',
                'db_table': 'paper',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('DBLP', models.URLField(blank=True, null=True)),
                ('GoogleScholar', models.URLField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Institution')),
            ],
            options={
                'verbose_name': '学者信息',
                'verbose_name_plural': '学者信息',
                'db_table': 'scholar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholar_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Area')),
                ('scholar_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar')),
            ],
            options={
                'verbose_name': '作者-领域信息',
                'verbose_name_plural': '作者-领域信息',
                'db_table': 'scholar_area',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Scholar_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Paper')),
                ('scholar_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar')),
            ],
            options={
                'verbose_name': '作者-论文信息',
                'verbose_name_plural': '作者-论文信息',
                'db_table': 'scholar_paper',
                'ordering': ['scholar_name'],
            },
        ),
    ]
