# Generated by Django 2.1.7 on 2019-03-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField()),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('cid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=40)),
                ('page', models.URLField()),
            ],
            options={
                'verbose_name': ' 会议信息',
                'verbose_name_plural': '会议信息',
                'db_table': 'conference',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': ' 期刊信息',
                'verbose_name_plural': '期刊信息',
                'db_table': 'journal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('pid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '学校信息',
                'verbose_name_plural': '学校信息',
                'db_table': 'school',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='authorship',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Paper'),
        ),
        migrations.AddField(
            model_name='author',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.School'),
        ),
    ]
