# Generated by Django 2.1.7 on 2019-04-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '领域信息',
                'verbose_name_plural': '领域信息',
                'db_table': 'area',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('DBLP', models.URLField(blank=True, null=True)),
                ('Href', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '会议信息',
                'verbose_name_plural': '会议信息',
                'db_table': 'conference',
                'ordering': ['name', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Conference_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Area')),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Conference')),
            ],
            options={
                'verbose_name': '会议-领域信息',
                'verbose_name_plural': '会议-领域信息',
                'db_table': 'conference_area',
                'ordering': ['area', 'conf_id'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('pub_cnt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
                'db_table': 'institution',
                'ordering': ['-pub_cnt', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '论文笔记',
                'verbose_name_plural': '论文笔记',
                'db_table': 'note',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('href', models.URLField(max_length=500)),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Conference')),
            ],
            options={
                'verbose_name': '论文信息',
                'verbose_name_plural': '论文信息',
                'db_table': 'paper',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('identity', models.CharField(choices=[('P', 'Professor'), ('S', 'Student')], default='S', max_length=10)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'profile',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('checked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Note')),
            ],
            options={
                'verbose_name': '笔记评论',
                'verbose_name_plural': '笔记评论',
                'db_table': 'remark',
                'ordering': ['content'],
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('DBLP', models.URLField(blank=True, null=True)),
                ('GoogleScholar', models.URLField(blank=True, null=True)),
                ('pub_cnt', models.IntegerField(default=0)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Institution')),
            ],
            options={
                'verbose_name': '学者信息',
                'verbose_name_plural': '学者信息',
                'db_table': 'scholar',
                'ordering': ['-pub_cnt', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scholar_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Area')),
                ('scholar_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar')),
            ],
            options={
                'verbose_name': '作者-领域信息',
                'verbose_name_plural': '作者-领域信息',
                'db_table': 'scholar_area',
                'ordering': ['area', 'scholar_name'],
            },
        ),
        migrations.CreateModel(
            name='Scholar_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Paper')),
                ('scholar_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar')),
            ],
            options={
                'verbose_name': '作者-论文信息',
                'verbose_name_plural': '作者-论文信息',
                'db_table': 'scholar_paper',
                'ordering': ['paper_title', 'scholar_name'],
            },
        ),
        migrations.CreateModel(
            name='User_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户关注领域',
                'verbose_name_plural': '用户关注领域信息',
                'db_table': 'user_area',
                'ordering': ['user', 'area'],
            },
        ),
        migrations.CreateModel(
            name='User_Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户关注会议',
                'verbose_name_plural': '用户关注会议信息',
                'db_table': 'user_conference',
                'ordering': ['user', 'conf'],
            },
        ),
        migrations.CreateModel(
            name='User_Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户关注学校',
                'verbose_name_plural': '用户关注学校信息',
                'db_table': 'user_institution',
                'ordering': ['user', 'ins'],
            },
        ),
        migrations.CreateModel(
            name='User_Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_paper', models.BooleanField(default=False)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户关注学者',
                'verbose_name_plural': '用户关注学者信息',
                'db_table': 'user_scholar',
                'ordering': ['user', 'sch'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='scholar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Paper'),
        ),
    ]
