# Generated by Django 2.1.7 on 2019-04-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='GoogleScholar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
