# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-28 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-conf_id__year'], 'verbose_name': '论文信息', 'verbose_name_plural': '论文信息'},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='year',
        ),
    ]
