# Generated by Django 2.1.7 on 2019-04-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0002_scholar_googlescholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar_area',
            name='scholar_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar'),
        ),
    ]
