# Generated by Django 2.1.7 on 2019-04-19 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSRanking', '0003_auto_20190405_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='m', max_length=10)),
                ('identity', models.CharField(choices=[('P', 'Professor'), ('S', 'Student')], default='S', max_length=10)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'profile',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='pub_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholar',
            name='pub_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
