# Generated by Django 2.1.7 on 2019-04-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0004_auto_20190419_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-pub_cnt', 'name'], 'verbose_name': '机构信息', 'verbose_name_plural': '机构信息'},
        ),
        migrations.AlterModelOptions(
            name='scholar',
            options={'ordering': ['-pub_cnt', 'name'], 'verbose_name': '学者信息', 'verbose_name_plural': '学者信息'},
        ),
    ]
