# Generated by Django 2.1.7 on 2019-04-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0005_auto_20190419_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['name', '-year'], 'verbose_name': '会议信息', 'verbose_name_plural': '会议信息'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year'], 'verbose_name': '论文信息', 'verbose_name_plural': '论文信息'},
        ),
    ]
