# Generated by Django 2.1.7 on 2019-04-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0007_auto_20190419_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Profile')),
            ],
            options={
                'verbose_name': '用户关注领域',
                'verbose_name_plural': '用户关注领域信息',
                'db_table': 'user_area',
                'ordering': ['user', 'area'],
            },
        ),
        migrations.CreateModel(
            name='User_Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Profile')),
            ],
            options={
                'verbose_name': '用户关注会议',
                'verbose_name_plural': '用户关注会议信息',
                'db_table': 'user_conference',
                'ordering': ['user', 'conf'],
            },
        ),
        migrations.CreateModel(
            name='User_Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Profile')),
            ],
            options={
                'verbose_name': '用户关注学校',
                'verbose_name_plural': '用户关注学校信息',
                'db_table': 'user_institution',
                'ordering': ['user', 'ins'],
            },
        ),
        migrations.CreateModel(
            name='User_Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Scholar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSRanking.Profile')),
            ],
            options={
                'verbose_name': '用户关注学者',
                'verbose_name_plural': '用户关注学者信息',
                'db_table': 'user_scholar',
                'ordering': ['user', 'sch'],
            },
        ),
    ]
