# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-21 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0011_note_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
