# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0012_auto_20190421_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
