# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0014_profile_scholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
