# Generated by Django 2.1.7 on 2019-04-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSRanking', '0015_remark_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_scholar',
            name='new_paper',
            field=models.BooleanField(default=False),
        ),
    ]
